### PR TITLE
Interaction User Story

### PR DESCRIPTION
**Pull request by kavyashivakumar**
Comments implemented and Added Interaction User story Swimlane

### CODE REVIEW

**Comment by mgasca** [comment]
For Citizen Redeem Points - Donation flow, I don't think they Browse Retailers.  They Browse Charities and just directly donate.  The points then become the Charities points and at some other time the Charity redemption flow occurs

**Comment by mgasca** [comment]
For Interaction Flow:  
I think we should include "Intrinsic Reward" into this, even though it's not mentioned in the use case

**Comment by kavyashivakumar** [comment]
> For Interaction Flow: I think we should consider including "Intrinsic Reward" into this, even though it's not mentioned in the use case

I have put this as a diff user story. will commit soon

**Comment by kavyashivakumar** [comment]
> For Citizen Redeem Points - Missing the Login at beginning. Donation flow, I don't think they Browse Retailers. They Browse Charities and just directly donate. The points then become the Charities points and at some other time the Charity redemption flow occurs

(I'll add the login. for the second part, are you implying police officers? because they do browse retailers in hey blue and can brose charities.  this is in kick off document.

**Comment by mgasca** [comment]
> > For Citizen Redeem Points - Missing the Login at beginning. Donation flow, I don't think they Browse Retailers. They Browse Charities and just directly donate. The points then become the Charities points and at some other time the Charity redemption flow occurs
> 
> (I'll add the login. for the second part, are you by any chance confusing with police officers? because they do browse retailers in hey blue and can brose charities. this is in kick off document.

Let me double check the kickoff.  I thought that Civilians just browsed Charities and donated points directly to Charities.  Then Charities choose how to spend the points (which you have captured in another flow)

**Comment by kapooruma** [comment]
> > > For Citizen Redeem Points - Missing the Login at beginning. Donation flow, I don't think they Browse Retailers. They Browse Charities and just directly donate. The points then become the Charities points and at some other time the Charity redemption flow occurs
> > 
> > 
> > (I'll add the login. for the second part, are you by any chance confusing with police officers? because they do browse retailers in hey blue and can brose charities. this is in kick off document.
> 
> Let me double check the kickoff. I thought that Civilians just browsed Charities and donated points directly to Charities. Then Charities choose how to spend the points (which you have captured in another flow)

I agree .. i understood that civilians just 'select' from the list of charities.... unlike retail shop or Municipality

**Pull request merged**
